// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZusSimulator.Data.BaseContext;

#nullable disable

namespace ZusSimulator.Data.Migrations
{
    [DbContext(typeof(ZusContext))]
    [Migration("20251004184910_addFormResultsAdvanced")]
    partial class addFormResultsAdvanced
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZusSimulator.Data.BaseContext.Entities.AdvancedFormResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("numeric");

                    b.Property<int>("CurrentAge")
                        .HasColumnType("integer");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<int>("RetirementAge")
                        .HasColumnType("integer");

                    b.Property<int>("SickLeaveDays")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubAccountBalance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("WorkStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AdvancedFormResults");
                });

            modelBuilder.Entity("ZusSimulator.Data.BaseContext.Entities.SimpleFormResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentAge")
                        .HasColumnType("integer");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InitialCapital")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MonthlyIncome")
                        .HasColumnType("numeric");

                    b.Property<int>("RetirementAge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WorkStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SimpleFormResults");
                });
#pragma warning restore 612, 618
        }
    }
}
